name: readyplato_workspace
environment:
  sdk: ">=3.11.1 <4.0.0"
dev_dependencies:
  melos: ^7.4.0
workspace: 

# ReadyPlato applications
 - apps/readyplato
 - apps/readyplato_admin
 - apps/readyplato_business

# Shared packages for these apps

 - packages/shared_core
 - packages/shared_db
 - packages/shared_ui
melos: 